apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-app
  template:
    metadata:
      labels:
        app: quarkus-app
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command: [ 'sh', '-c', 'until nslookup rabbitmq && nc -zv rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;' ]
      containers:
        - name: quarkus-app
          image: quarkus-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"