<wsdl:definitions name="LIHBMessageService" targetNamespace="http://uic.cc.org/UICMessage"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://uic.cc.org/UICMessage"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xs:schema targetNamespace="http://uic.cc.org/UICMessage" version="1.0"
                   xmlns:tns="http://uic.cc.org/UICMessage" xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:element name="UICHBMessage" type="tns:UICHBMessage"/>
            <xs:element name="UICHBMessageResponse" type="tns:UICHBMessageResponse"/>
            <xs:complexType name="UICHBMessage">
                <xs:sequence>
                    <xs:element minOccurs="0" name="message" type="xs:anyType"/>
                    <xs:element minOccurs="0" name="properties" type="xs:anyType"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="UICHBMessageResponse">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="return" type="xs:anyType"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="UICHBMessageResponse">
        <wsdl:part element="tns:UICHBMessageResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="UICHBMessage">
        <wsdl:part element="tns:UICHBMessage" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="UICHBMessage">
        <wsdl:operation name="UICHBMessage">
            <wsdl:input message="tns:UICHBMessage" name="UICHBMessage"/>
            <wsdl:output message="tns:UICHBMessageResponse" name="UICHBMessageResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="LIHBMessageServiceSoapBinding" type="tns:UICHBMessage">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="UICHBMessage">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="UICHBMessage">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="UICHBMessageResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="LIHBMessageService">
        <wsdl:port binding="tns:LIHBMessageServiceSoapBinding" name="UICHBMessagePort">
            <soap:address location="https://SLW1095/LIServices/LIHBMessage"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>